apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Gi              # Total storage
  accessModes:
    - ReadWriteOnce           # One node access
  hostPath:
    path: /mnt/nginx-data           # Local path (Minikube only)