apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache-prod
  labels:
    app: apache
spec:
  type: NodePort

  selector:
    app: apache

  ports:
  - name: http   # ✅ Naming port (best practice)
    port: 80
    targetPort: 80
    nodePort: 30008