#!/usr/bin/env bash

# VARIABLES

# REGION
REGION="us-east-1"
AZ="us-east-1a"

# VPC
VPC_NAMES=("ntier-1" "ntier-2")
VPC_CIDRS=("10.0.0.0/16" "10.1.0.0/16")

# SUBNETS
PUBLIC_SUBNET_CIDR=("10.10.1.0/24" "10.10.2.0/24")
PRIVATE_SUBNET_CIDR=("10.10.3.0/24" "10.10.4.0/24")
PUBLIC_SUBNET_NAME="ntier_subnet_public"
PRIVATE_SUBNET_NAME="ntier_subnet_private"

# INTERNET GATEWAY
IGW_NAME=("ntier1-igw" "ntier2-igw")

# EC2
INSTANCE_TYPE="t3.micro"
INSTANCE_TAG_NAME="web-1"
KEY_NAME="hazarath"

# SECURITY GROUP
SG_TAG_NAME="ntier1sg"
SG_COUNT ="1"                 # number of SGs per VPC
SECURITY_GROUP_ID_TCP_CIDR_RANGE="0.0.0.0/0"

# Route table

PUBLIC_RT_NAME="ntier_rt_public_${INDEX}"
PRIVATE_RT_NAME="ntier_rt_private_${INDEX}"
